version: '3.9'
services:
  fc_catalogo:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    command: sh run.sh
    ports:
      - 8080:8080
      - 8005:5005
